"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { 
  ShieldCheck, 
  ChevronLeft, 
  Copy, 
  Check, 
  Trash2,
  Settings2,
  FileMinus,
  AlignLeft,
  FileCode2
} from "lucide-react";
import ToolInfo from "@/components/tools/ToolInfo";

export default function StripHtmlClient() {
  const [inputText, setInputText] = useState("");
  const [outputText, setOutputText] = useState("");
  
  // Settings State
  const [removeScripts, setRemoveScripts] = useState(true);
  const [preserveSpacing, setPreserveSpacing] = useState(true);
  const [collapseWhitespace, setCollapseWhitespace] = useState(false);
  
  // Analytics State
  const [copied, setCopied] = useState(false);
  const [charCount, setCharCount] = useState(0);

  useEffect(() => {
    if (!inputText) {
      setOutputText("");
      setCharCount(0);
      return;
    }

    let processedHtml = inputText;

    // Smart Spacing: Convert HTML block elements to actual text line breaks before stripping
    if (preserveSpacing) {
      processedHtml = processedHtml.replace(/<br\s*\/?>/gi, '\n');
      // Use $1 to keep the closing tags intact so DOMParser doesn't break, just append newlines
      processedHtml = processedHtml.replace(/(<\/p>|<\/div>|<\/h[1-6]>|<\/script>|<\/style>)/gi, '$1\n\n');
      processedHtml = processedHtml.replace(/<li[^>]*>/gi, '\n• ');
    }

    try {
      // Use the native browser DOMParser to safely extract text
      const parser = new DOMParser();
      const doc = parser.parseFromString(processedHtml, 'text/html');

      // Strip out scripts, styles, and noscript tags to prevent code leakage
      if (removeScripts) {
        const unwantedTags = doc.querySelectorAll('script, style, noscript');
        unwantedTags.forEach(el => el.remove());
      }

      // CRITICAL FIX: Extract text from documentElement, not body. 
      // DOMParser automatically relocates <script> and <style> tags to the <head>,
      // so if we only read the body, we miss them entirely!
      let text = doc.documentElement.textContent || "";

      // Optional: Collapse multiple spaces and blank lines
      if (collapseWhitespace) {
        text = text.replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim();
      } else if (preserveSpacing) {
        // Clean up excessive newlines generated by block conversion
        text = text.replace(/\n{3,}/g, '\n\n').trim();
      }

      setOutputText(text);
      setCharCount(text.length);
    } catch (e) {
      setOutputText("Error parsing HTML.");
    }

  }, [inputText, removeScripts, preserveSpacing, collapseWhitespace]);

  const clearAll = () => {
    setInputText("");
    setOutputText("");
    setCharCount(0);
  };

  const copyToClipboard = () => {
    if (!outputText) return;
    navigator.clipboard.writeText(outputText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const aboutDescription = (
    <>
      <p className="mb-4">
        The HTML Tag Stripper is a data-cleaning utility that instantly extracts raw, readable text from complex HTML structures. When you copy content from a rich-text editor, a web page source, or a formatted email, hidden HTML tags often travel with it.
      </p>
      <p>
        This tool uses your browser's native DOM Parsing engine to accurately isolate text. Advanced modifiers allow you to safely purge background scripts or CSS styling, while intelligently converting HTML block elements (like <code>&lt;br&gt;</code> and <code>&lt;p&gt;</code>) into physical line breaks so your text remains highly readable.
      </p>
    </>
  );

  const howToSteps = [
    {
      title: "Input your Code",
      description: "Paste your raw HTML payload, website source code, or rich text into the Original Content panel.",
    },
    {
      title: "Adjust Modifiers",
      description: "Use the execution criteria to decide if you want to preserve structural line breaks, purge background scripts, or collapse heavy spacing.",
    },
    {
      title: "Copy the Result",
      description: "Click the 'Copy Result' button to grab the clean, unformatted plaintext output for your documents.",
    },
  ];

  const faqs = [
    {
      question: "Why do I see CSS code in my output?",
      answer: "If the HTML you pasted includes a <style> block, a standard tag stripper will leave the raw CSS text behind. Ensure the 'Purge Scripts & Styles' modifier is active to automatically delete those blocks before extraction.",
    },
    {
      question: "What does 'Preserve Structural Spacing' do?",
      answer: "By default, browsers ignore physical line breaks in HTML and rely on tags like <p> or <br>. This setting analyzes your HTML and injects physical line breaks where those structural tags exist, preventing your extracted text from collapsing into one massive paragraph.",
    },
    {
      question: "Is my source code sent to a server?",
      answer: "No. The entire extraction process happens securely within your browser's local memory using the native DOMParser API. Your code is never transmitted externally.",
    },
  ];

  return (
    <div className="min-h-screen">
      <div className="px-6 py-12 text-center sm:py-16">
        <Link 
          href="/" 
          className="inline-flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-blue-400 transition-colors mb-4"
        >
          <ChevronLeft className="h-4 w-4" /> Back to Utilities
        </Link>
        <h1 className="mb-4 text-3xl font-extrabold tracking-tight text-white sm:text-5xl">
          Strip HTML <span className="text-blue-400">Tags</span>
        </h1>
        <p className="mx-auto max-w-2xl text-sm font-medium text-slate-300 sm:text-base md:text-lg">
          Extract clean, raw text from complex HTML source code instantly.
        </p>
        <div className="mx-auto mt-6 flex max-w-fit items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-4 py-2 text-xs font-medium text-emerald-300 shadow-sm backdrop-blur-sm sm:text-sm">
          <ShieldCheck className="h-4 w-4 shrink-0" />
          Whenever possible, your data never leaves your device. Your security is our priority.
        </div>
      </div>

      <div className="mx-auto max-w-6xl px-4 pb-12 sm:px-6">
        <div className="rounded-2xl border border-slate-700 bg-[#95BDD7] p-5 shadow-xl sm:p-8 lg:rounded-3xl">
          
          {/* Header Control Panel */}
          <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-700/20 pb-4 gap-4">
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-blue-600 p-2 text-white shadow-sm">
                <FileMinus className="h-5 w-5" />
              </div>
              <h2 className="text-xl font-bold text-gray-900">Text Extractor</h2>
            </div>
            
            <button
              onClick={clearAll}
              disabled={!inputText}
              className="flex items-center justify-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-bold text-red-600 shadow-sm transition-all hover:bg-red-50 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Trash2 className="h-4 w-4" /> Clear All
            </button>
          </div>

          <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
            
            {/* LEFT SIDE: Inputs and Outputs */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="flex flex-col">
                <div className="mb-2 flex items-center justify-between">
                  <label className="text-sm font-bold text-slate-800">HTML Source Code</label>
                </div>
                <textarea
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Paste your raw HTML here (e.g., <p>Hello <strong>World</strong></p>)..."
                  className="h-[250px] sm:h-[350px] lg:h-[450px] w-full resize-none rounded-xl border border-slate-400 bg-white p-4 font-mono text-sm text-slate-900 focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-600/20 shadow-inner custom-scrollbar"
                />
              </div>

              <div className="flex flex-col">
                <div className="mb-2 flex items-center justify-between">
                  <label className="text-sm font-bold text-slate-800">Extracted Plaintext</label>
                  <button
                    onClick={copyToClipboard}
                    disabled={!outputText}
                    className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-bold text-white transition-colors disabled:opacity-40 disabled:cursor-not-allowed ${copied ? "bg-emerald-600" : "bg-blue-600 hover:bg-blue-700"}`}
                  >
                    {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />} 
                    {copied ? "Copied" : "Copy Result"}
                  </button>
                </div>
                <textarea
                  readOnly
                  value={outputText}
                  placeholder="Your clean text will display here..."
                  className="h-[250px] sm:h-[350px] lg:h-[450px] w-full resize-none rounded-xl border border-slate-300 bg-slate-100 p-4 font-mono text-sm text-slate-900 focus:outline-none shadow-inner custom-scrollbar"
                />
              </div>
            </div>

            {/* RIGHT SIDE: Configuration Panel */}
            <div className="flex flex-col space-y-5 h-full">
              
              <div className="rounded-xl border border-slate-300 bg-slate-100/50 p-4 shadow-inner">
                <div className="flex items-center gap-2 border-b border-slate-300 pb-2.5 text-slate-800 mb-4">
                  <Settings2 className="h-4 w-4" />
                  <h3 className="font-bold text-sm">Execution Criteria</h3>
                </div>

                <div className="space-y-4">
                  <label className="flex cursor-pointer items-start justify-between gap-3 text-sm text-slate-800">
                    <div className="flex flex-col">
                      <span className="font-bold">Purge Scripts & Styles</span>
                      <span className="text-xs text-slate-500 mt-0.5">Removes injected JavaScript and CSS code blocks from the output.</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={removeScripts}
                      onChange={(e) => setRemoveScripts(e.target.checked)}
                      className="mt-1 h-4 w-4 shrink-0 rounded border-slate-400 text-blue-600 focus:ring-blue-500"
                    />
                  </label>

                  <label className="flex cursor-pointer items-start justify-between gap-3 text-sm text-slate-800">
                    <div className="flex flex-col">
                      <span className="font-bold">Preserve Structural Spacing</span>
                      <span className="text-xs text-slate-500 mt-0.5">Converts structural tags (like &lt;br&gt; and &lt;p&gt;) into physical line breaks.</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={preserveSpacing}
                      onChange={(e) => setPreserveSpacing(e.target.checked)}
                      className="mt-1 h-4 w-4 shrink-0 rounded border-slate-400 text-blue-600 focus:ring-blue-500"
                    />
                  </label>

                  <label className="flex cursor-pointer items-start justify-between gap-3 text-sm text-slate-800">
                    <div className="flex flex-col">
                      <span className="font-bold">Collapse Whitespace</span>
                      <span className="text-xs text-slate-500 mt-0.5">Trims trailing spaces and merges huge gaps into single line breaks.</span>
                    </div>
                    <input
                      type="checkbox"
                      checked={collapseWhitespace}
                      onChange={(e) => setCollapseWhitespace(e.target.checked)}
                      className="mt-1 h-4 w-4 shrink-0 rounded border-slate-400 text-blue-600 focus:ring-blue-500"
                    />
                  </label>
                </div>
              </div>

              {/* Status Box */}
              <div className="mt-auto rounded-xl bg-slate-900 p-4 text-white shadow-md">
                <div className="flex items-center gap-2 border-b border-slate-800 pb-2 mb-2">
                  <AlignLeft className="h-4 w-4 text-blue-400" />
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Output Analytics</span>
                </div>
                <div className="flex justify-between font-mono text-sm">
                  <span className="text-slate-400">Final Length:</span>
                  <span className="font-bold text-emerald-400">{charCount} Chars</span>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      <ToolInfo 
        aboutDescription={aboutDescription}
        howTo={howToSteps}
        faqs={faqs}
      />
    </div>
  );
}